defmodule Vachan.Repo.Migrations.ListNameUniqueConstraint do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:crm_lists, [:name], name: "crm_lists_unique_list_name_index")
  end

  def down do
    drop_if_exists unique_index(:crm_lists, [:name], name: "crm_lists_unique_list_name_index")
  end
end
