defmodule Vachan.Repo.Migrations.AddSenderInfoToCampaigns do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:campaigns) do
      add :sender_name, :text, null: false
      add :sender_email, :text, null: false
      add :reply_to_email, :text, null: false
      add :reply_to_name, :text, null: false
      add :status, :text, null: false, default: "draft"
      add :active, :boolean, null: false, default: true
    end
  end

  def down do
    alter table(:campaigns) do
      remove :active
      remove :status
      remove :reply_to_name
      remove :reply_to_email
      remove :sender_email
      remove :sender_name
    end
  end
end