defmodule Vachan.Repo.Migrations.Timestamps do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:templates) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:people) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:messages) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:massmail_events) do
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:crm_lists) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    alter table(:campaigns) do
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end
  end

  def down do
    alter table(:campaigns) do
      remove :updated_at
      remove :created_at
    end

    alter table(:crm_lists) do
      remove :updated_at
      remove :created_at
    end

    alter table(:massmail_events) do
      remove :updated_at
    end

    alter table(:messages) do
      remove :updated_at
      remove :created_at
    end

    alter table(:people) do
      remove :updated_at
      remove :created_at
    end

    alter table(:templates) do
      remove :updated_at
      remove :created_at
    end
  end
end
