defmodule Vachan.Repo.Migrations.Rename do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:messages), :receipient_id, to: :recepient_id
  end

  def down do
    rename table(:messages), :recepient_id, to: :receipient_id
  end
end
