defmodule Vachan.Repo.Migrations.PrelaunchTable do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:subscribers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :email, :citext, null: false
      add :name, :text, null: false
      add :join_beta_tester, :boolean, null: false, default: false
      add :subscribe_newsletter, :boolean, null: false, default: false
      add :created_at, :utc_datetime_usec, null: false, default: fragment("now()")
      add :updated_at, :utc_datetime_usec, null: false, default: fragment("now()")
    end

    create unique_index(:subscribers, [:email], name: "subscribers_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:subscribers, [:email], name: "subscribers_unique_email_index")

    drop table(:subscribers)
  end
end
