defmodule Vachan.Repo.Migrations.CrmAndMail2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:crm_people_lists) do
      modify :list_id, :bigint
    end
  end

  def down do
    alter table(:crm_people_lists) do
      modify :list_id, :uuid
    end
  end
end