defmodule Vachan.Repo.Migrations.MigrateResources4 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:sender_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v4()"), primary_key: true
      add :provider, :text, null: false, default: "smtp"
      add :username, :text
      add :password, :text
      add :api_key, :text
      add :smtp_host, :text
      add :smtp_port, :text
      add :name, :text, null: false
      add :email, :citext, null: false
      add :title, :text, null: false

      add :organization_id,
          references(:organizations,
            column: :id,
            name: "sender_profiles_organization_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end

    alter table(:campaigns) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :sender_email

      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      remove :sender_name

      add :sender_profile_id,
          references(:sender_profiles,
            column: :id,
            name: "campaigns_sender_profile_id_fkey",
            type: :uuid,
            prefix: "public"
          )
    end
  end

  def down do
    drop_if_exists constraint(:campaigns, "campaigns_sender_profile_id_fkey")

    alter table(:campaigns) do
      remove :sender_profile_id
      # This is the `down` migration of the statement:
      #
      #     remove :sender_name
      #

      add :sender_name, :text, null: false
      # This is the `down` migration of the statement:
      #
      #     remove :sender_email
      #

      add :sender_email, :text, null: false
    end

    drop constraint(:sender_profiles, "sender_profiles_organization_id_fkey")

    drop table(:sender_profiles)
  end
end
